apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: hanchenjhc/pal-tracker:v1
          envFrom:
            - secretRef:
                name: db-credentials
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "10"]
          resources:
            limits:
              cpu: "100m"
          env:
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: welcome.message
